# Test
---
packages:
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python-pip

# Dictionary with pip dependencies
pip_dependencies:
    - docker-py