# Test
---
packages:
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

localhost_packages:
    - urllib3
    - pyOpenSSL
    - ndg-httpsclient
    - pyasn1

# Dictionary with pip dependencies
pip_dependencies:
  docker-py: 1.7.0